In [5]:
import numpy as np

In [ ]:
# Create a 1d array of numbers from 0 to 9

In [39]:
n = np.arange(10)
print(n)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
'''
Extract all odd numbers from arr
Replace all odd numbers in arr with -1
'''

In [41]:
n[n % 2 != 0]

array([1, 3, 5, 7, 9])

In [43]:
n[n % 2 != 0]  = -1
n

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
'''
Convert a 1d arr to a 2d arr with 2 rows
'''

In [45]:
n.reshape ((2,5))

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

In [ ]:
'''
- Get the common items between a and b using intersect1d
'''

In [82]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,4,5,5,9])
c = np.intersect1d(a,b)
#C1
for i in c:
    count_a = 0
    count_b = 0
    for j in a:
        if j == i:
            count_a += 1
    for j in b:
        if j == i:
            count_b +=1
    print(f"Số {i} xuất hiện {count_a} lần trong a và {count_b} lần trong b.")  
print('------------------------------------------------------------------------------')
#C2
for i in c:
    count_a = np.count_nonzero(a == i)
    count_b = np.count_nonzero(b == i)
    print(f"Số {i} xuất hiện {count_a} lần trong a và {count_b} lần trong b.")

Số 1 xuất hiện 1 lần trong a và 1 lần trong b.
Số 4 xuất hiện 1 lần trong a và 1 lần trong b.
Số 5 xuất hiện 1 lần trong a và 2 lần trong b.
Số 9 xuất hiện 1 lần trong a và 1 lần trong b.
------------------------------------------------------------------------------
Số 1 xuất hiện 1 lần trong a và 1 lần trong b.
Số 4 xuất hiện 1 lần trong a và 1 lần trong b.
Số 5 xuất hiện 1 lần trong a và 2 lần trong b.
Số 9 xuất hiện 1 lần trong a và 1 lần trong b.


In [ ]:
'''
- From arr a, remove all items present in arr b using setdiff1d
'''

In [86]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,4,5,5,9])
c = np.setdiff1d(a,b)
c

array([2, 3, 6, 7, 8])

In [ ]:
'''
- Get all items between 5 and 10 from a
'''

In [100]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a[(a >= 5) & (a <= 10)]
b

array([5, 6, 7, 8, 9])

In [ ]:
'''
Swap columns 1 and 2 in the array and rows
'''

In [140]:
arr = np.arange(9).reshape(3,3)
print(arr[:,[2,1,0]])
print(arr[[1,2,0]])

[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[3 4 5]
 [6 7 8]
 [0 1 2]]


In [150]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter= ',', dtype='object')
sepallength = np.genfromtxt(url, delimiter= ',', dtype='float', usecols=[0])
sepallength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [162]:
print(np.mean(sepallength, axis=0)) #Neu 1d thi khong can axis
print(np.mean(sepallength))
# print(np.mean(sepallength, axis=1)) ERROR
print(np.median(sepallength, axis=0))

5.843333333333334
5.843333333333334
5.8


In [ ]:
'''
Compute the maximum for each row in the given arr
'''

In [170]:
a = np.random.randint(1, 10, [3,5])
a

array([[4, 9, 7, 1, 7],
       [4, 9, 2, 7, 1],
       [5, 6, 1, 2, 3]])

In [174]:
np.max(a, axis = 1)

array([9, 9, 6])