# Luu y:
- Numpy is meteral but only change value and NOT del, add

In [5]:
import numpy as np

In [9]:
l = [1,2,3,4]
l2 = ['thanh tuan']
n = np.array(l)
print(n)
print(n.dtype)

[1 2 3 4]
int32


In [11]:
a = np.arange(10)
print(a)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
int32


In [23]:
a = np.array([[1,5], [2,4]])
a

array([[1, 5],
       [2, 4]])

In [27]:
a = np.arange(10)
a[0] = 4444
print(a)

[4444    1    2    3    4    5    6    7    8    9]


In [31]:
a = np.array([1,2,3,True])
print(a)

[1 2 3 1]


In [53]:
#Other methods to create arrays
# zeros / ones / full / eye / random
a = np.zeros((3,3))       # zeros((row, column, replace))
print(a)

a = np.ones((2,2))
print(a)

a = np.full((2,2), 7)
print(a)

a = np.eye(4)
print(a)

a = np.random.random((2,2))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.26500877 0.84781843]
 [0.5825099  0.56399178]]


In [ ]:
# Infor Numpy

In [59]:
# SIZE
a = np.array([1,2,3,4,5,6])
b = np.array([[1,2], [3,5]])
print(len(a))
print(len(b))
print('---------')
print(a.size)
print(b.size)

#SHAPE vs DIMENSION
print(a.shape)
print(b.shape)

print(a.ndim)
print(b.ndim)

6
2
---------
6
4
(6,)
(2, 2)
1
2


# Array Math

In [45]:
x = np.array([[1,2,3], [4,5,6]], dtype= np.float64)
y = np.array([[1,4,5], [2,6,1]], dtype= np.float64)
# Sum Sub Divid Mathli
print(x)
print(y)
print('------------------------------------')
# Dot matrix
# print(x.dot(y))

# Sum and axis
print(np.sum(x, axis = 0)) #Row
print('------------------------------------')
print(np.sum(y, axis = 1)) #Column
print('------------------------------------')
#Transpose matrix
print(x)
print('------------------------------------')
print(x.T)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 4. 5.]
 [2. 6. 1.]]
------------------------------------
[5. 7. 9.]
------------------------------------
[10.  9.]
------------------------------------
[[1. 2. 3.]
 [4. 5. 6.]]
------------------------------------
[[1. 4.]
 [2. 5.]
 [3. 6.]]


# Vectorization

In [48]:
import timeit

In [66]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [68]:
# Sum vs for
print([x + 10 for x in a])
print(timeit.timeit(setup= 'import numpy as np', stmt='[x + 10 for x in np.arange(10)]'))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
3.795650600019144


In [69]:
# Sum with vectorization
print(a + 10)
print(timeit.timeit(setup= 'import numpy as np', stmt='np.arange(10) + 10'))

[10 11 12 13 14 15 16 17 18 19]
2.718263199989451


# Masking

In [78]:
a = np.random.randint(-10, 10, size = 10) 
print(a)

[ 2  5  4 -1 -3  5  5 -9  2 -8]


In [94]:
# a > 0
print(a[a > 0]) #C1
print('------------------------------------')
b = a > 0
print(a[b])
print('------------------------------------')
# element  %  2 == 0
print(a[a % 2 == 0])

[2 5 4 5 5 2]
------------------------------------
[2 5 4 5 5 2]
------------------------------------
[ 2  4  2 -8]


In [96]:
# ALL and ANY
print(np.all(a > 0))
print('------------------------------------')
print(np.any(a > 0))

False
------------------------------------
True


In [ ]:
# Different bewteen MEAN and MEDIAN
'''
- Nếu Mean = 5 nhưng Median = 8 => Có sự sai lệch data
- Nhìn MIN -> MAX -> MEAN ->  MEDIAN
'''